-- AlterEnum: new manual vendors before OTHER (order: PLAID … FLIPSNACK OTHER)
ALTER TYPE "AiProvider" ADD VALUE 'DROPBOX' BEFORE 'OTHER';
ALTER TYPE "AiProvider" ADD VALUE 'GOOGLE_CLOUD_STORAGE' BEFORE 'OTHER';
ALTER TYPE "AiProvider" ADD VALUE 'DOCSEND' BEFORE 'OTHER';
ALTER TYPE "AiProvider" ADD VALUE 'FLIPSNACK' BEFORE 'OTHER';
