-- AlterEnum: Lovable, Linear, Vercel-adjacent SaaS (VERCEL already exists)
ALTER TYPE "AiProvider" ADD VALUE 'RAILWAY' BEFORE 'OTHER';
ALTER TYPE "AiProvider" ADD VALUE 'NOTION' BEFORE 'OTHER';
ALTER TYPE "AiProvider" ADD VALUE 'NETLIFY' BEFORE 'OTHER';
ALTER TYPE "AiProvider" ADD VALUE 'LOVABLE' BEFORE 'OTHER';
ALTER TYPE "AiProvider" ADD VALUE 'LINEAR' BEFORE 'OTHER';
ALTER TYPE "AiProvider" ADD VALUE 'GITHUB' BEFORE 'OTHER';
ALTER TYPE "AiProvider" ADD VALUE 'FIGMA' BEFORE 'OTHER';
